import { Inter } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react"; 


const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"]
});


export const metadata = {
  title: "Pinpoints Nigeria Ltd",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
          {children}
          <Analytics/>
      </body>
    </html>
  );
}

